/* Mock Data for Smart Hostel Management System */

// Student users
export const students = [
  {
    id: 'STU001',
    name: 'Rahul Sharma',
    regNumber: 'REG2024001',
    email: 'rahul@university.edu',
    password: 'password123',
    hostelBlock: 'A',
    roomNumber: '101',
    role: 'student',
  },
  {
    id: 'STU002',
    name: 'Priya Patel',
    regNumber: 'REG2024002',
    email: 'priya@university.edu',
    password: 'password123',
    hostelBlock: 'B',
    roomNumber: '205',
    role: 'student',
  },
  {
    id: 'STU003',
    name: 'Amit Kumar',
    regNumber: 'REG2024003',
    email: 'amit@university.edu',
    password: 'password123',
    hostelBlock: 'A',
    roomNumber: '312',
    role: 'student',
  },
  {
    id: 'STU004',
    name: 'Vats Demo',
    regNumber: 'vats',
    email: 'vats',
    password: 'vats1234',
    hostelBlock: 'C',
    roomNumber: '404',
    role: 'student',
  },
];

// Staff members
export const staffMembers = [
  {
    id: 'STF001',
    name: 'Rajesh Verma',
    email: 'rajesh@university.edu',
    password: 'password123',
    role: 'staff',
    specialization: 'Electrical',
    phone: '9876543210',
  },
  {
    id: 'STF002',
    name: 'Suresh Yadav',
    email: 'suresh@university.edu',
    password: 'password123',
    role: 'staff',
    specialization: 'Plumbing',
    phone: '9876543211',
  },
  {
    id: 'STF003',
    name: 'Manoj Singh',
    email: 'manoj@university.edu',
    password: 'password123',
    role: 'staff',
    specialization: 'WiFi',
    phone: '9876543212',
  },
  {
    id: 'STF004',
    name: 'Deepak Gupta',
    email: 'deepak@university.edu',
    password: 'password123',
    role: 'staff',
    specialization: 'Furniture',
    phone: '9876543213',
  },
  {
    id: 'STF005',
    name: 'Vats Demo',
    email: 'vats',
    password: 'vats1234',
    role: 'staff',
    specialization: 'General',
    phone: '9876543214',
  },
];

// Admin users
export const admins = [
  {
    id: 'ADM001',
    name: 'Dr. Anand Mishra',
    email: 'admin@university.edu',
    password: 'admin123',
    role: 'admin',
    designation: 'Chief Warden',
  },
  {
    id: 'ADM002',
    name: 'Prof. Sunita Joshi',
    email: 'warden@university.edu',
    password: 'admin123',
    role: 'admin',
    designation: 'Hostel Warden',
  },
  {
    id: 'ADM003',
    name: 'Vats Demo',
    email: 'vats',
    password: 'vats1234',
    role: 'admin',
    designation: 'Demo Admin',
  },
];

// Complaints
export const complaints = [
  {
    id: 'CMP001',
    studentId: 'STU001',
    studentName: 'Rahul Sharma',
    hostelBlock: 'A',
    roomNumber: '101',
    category: 'Electrical',
    description: 'Ceiling fan not working in room 101. It makes a loud noise and stops intermittently.',
    status: 'Pending',
    priority: 'High',
    assignedStaff: null,
    assignedStaffName: null,
    createdAt: '2026-02-01T10:30:00',
    updatedAt: '2026-02-01T10:30:00',
    resolutionNotes: '',
    image: null,
  },
  {
    id: 'CMP002',
    studentId: 'STU001',
    studentName: 'Rahul Sharma',
    hostelBlock: 'A',
    roomNumber: '101',
    category: 'Plumbing',
    description: 'Water leakage in bathroom. The tap is dripping continuously and wasting water.',
    status: 'In Progress',
    priority: 'Medium',
    assignedStaff: 'STF002',
    assignedStaffName: 'Suresh Yadav',
    createdAt: '2026-02-03T14:20:00',
    updatedAt: '2026-02-05T09:15:00',
    resolutionNotes: 'Identified the issue, replacement parts ordered.',
    image: null,
  },
  {
    id: 'CMP003',
    studentId: 'STU002',
    studentName: 'Priya Patel',
    hostelBlock: 'B',
    roomNumber: '205',
    category: 'WiFi',
    description: 'WiFi connectivity is very poor in Block B, second floor. Unable to attend online classes.',
    status: 'Resolved',
    priority: 'High',
    assignedStaff: 'STF003',
    assignedStaffName: 'Manoj Singh',
    createdAt: '2026-01-28T08:00:00',
    updatedAt: '2026-02-01T16:45:00',
    resolutionNotes: 'Router replaced and signal booster installed.',
    image: null,
  },
  {
    id: 'CMP004',
    studentId: 'STU002',
    studentName: 'Priya Patel',
    hostelBlock: 'B',
    roomNumber: '205',
    category: 'Furniture',
    description: 'Study table drawer is broken. Cannot store books properly.',
    status: 'Pending',
    priority: 'Low',
    assignedStaff: null,
    assignedStaffName: null,
    createdAt: '2026-02-10T11:00:00',
    updatedAt: '2026-02-10T11:00:00',
    resolutionNotes: '',
    image: null,
  },
  {
    id: 'CMP005',
    studentId: 'STU003',
    studentName: 'Amit Kumar',
    hostelBlock: 'A',
    roomNumber: '312',
    category: 'Sanitation',
    description: 'Common washroom on 3rd floor not cleaned for 2 days. Very unhygienic conditions.',
    status: 'In Progress',
    priority: 'High',
    assignedStaff: 'STF002',
    assignedStaffName: 'Suresh Yadav',
    createdAt: '2026-02-08T07:30:00',
    updatedAt: '2026-02-09T10:00:00',
    resolutionNotes: 'Cleaning staff notified. Deep cleaning scheduled.',
    image: null,
  },
  {
    id: 'CMP006',
    studentId: 'STU003',
    studentName: 'Amit Kumar',
    hostelBlock: 'A',
    roomNumber: '312',
    category: 'Electrical',
    description: 'Power socket near study table is not working. Sparking observed.',
    status: 'Pending',
    priority: 'High',
    assignedStaff: 'STF001',
    assignedStaffName: 'Rajesh Verma',
    createdAt: '2026-02-12T09:45:00',
    updatedAt: '2026-02-12T09:45:00',
    resolutionNotes: '',
    image: null,
  },
  {
    id: 'CMP007',
    studentId: 'STU001',
    studentName: 'Rahul Sharma',
    hostelBlock: 'A',
    roomNumber: '101',
    category: 'Other',
    description: 'Room door lock is jammed. Difficulty in opening and closing.',
    status: 'Resolved',
    priority: 'Medium',
    assignedStaff: 'STF004',
    assignedStaffName: 'Deepak Gupta',
    createdAt: '2026-01-15T13:00:00',
    updatedAt: '2026-01-18T11:30:00',
    resolutionNotes: 'Lock replaced with new one. Keys handed to student.',
    image: null,
  },
  {
    id: 'CMP008',
    studentId: 'STU002',
    studentName: 'Priya Patel',
    hostelBlock: 'B',
    roomNumber: '205',
    category: 'Plumbing',
    description: 'Hot water geyser not functioning. No hot water supply for past 3 days.',
    status: 'In Progress',
    priority: 'Medium',
    assignedStaff: 'STF002',
    assignedStaffName: 'Suresh Yadav',
    createdAt: '2026-02-11T06:30:00',
    updatedAt: '2026-02-12T14:00:00',
    resolutionNotes: 'Heating element needs replacement. Parts sourced.',
    image: null,
  },
  {
    id: 'CMP009',
    studentId: 'STU004',
    studentName: 'Vats Demo',
    hostelBlock: 'C',
    roomNumber: '404',
    category: 'Electrical',
    description: 'Power socket not working near bed. Need urgent repair.',
    status: 'Pending',
    priority: 'High',
    assignedStaff: 'STF005',
    assignedStaffName: 'Vats Demo',
    createdAt: '2026-02-13T08:00:00',
    updatedAt: '2026-02-13T08:00:00',
    resolutionNotes: '',
    image: null,
  },
  {
    id: 'CMP010',
    studentId: 'STU004',
    studentName: 'Vats Demo',
    hostelBlock: 'C',
    roomNumber: '404',
    category: 'WiFi',
    description: 'Poor WiFi signal in room. Cannot attend online classes properly.',
    status: 'In Progress',
    priority: 'High',
    assignedStaff: 'STF005',
    assignedStaffName: 'Vats Demo',
    createdAt: '2026-02-12T10:30:00',
    updatedAt: '2026-02-13T09:00:00',
    resolutionNotes: 'Checking router configuration.',
    image: null,
  },
  {
    id: 'CMP011',
    studentId: 'STU004',
    studentName: 'Vats Demo',
    hostelBlock: 'C',
    roomNumber: '404',
    category: 'Furniture',
    description: 'Study table drawer is broken. Cannot store books.',
    status: 'Resolved',
    priority: 'Low',
    assignedStaff: 'STF005',
    assignedStaffName: 'Vats Demo',
    createdAt: '2026-02-10T14:00:00',
    updatedAt: '2026-02-11T16:00:00',
    resolutionNotes: 'Drawer repaired and reinforced with new screws.',
    image: null,
  },
  {
    id: 'CMP012',
    studentId: 'STU004',
    studentName: 'Vats Demo',
    hostelBlock: 'C',
    roomNumber: '404',
    category: 'Sanitation',
    description: 'Bathroom drain is clogged. Water not draining.',
    status: 'Pending',
    priority: 'Medium',
    assignedStaff: null,
    assignedStaffName: null,
    createdAt: '2026-02-13T07:00:00',
    updatedAt: '2026-02-13T07:00:00',
    resolutionNotes: '',
    image: null,
  },
  {
    id: 'CMP013',
    studentId: 'STU001',
    studentName: 'Rahul Sharma',
    hostelBlock: 'A',
    roomNumber: '101',
    category: 'Plumbing',
    description: 'Tap water pressure is very low. Difficult to wash.',
    status: 'Pending',
    priority: 'Medium',
    assignedStaff: 'STF005',
    assignedStaffName: 'Vats Demo',
    createdAt: '2026-02-13T09:30:00',
    updatedAt: '2026-02-13T09:30:00',
    resolutionNotes: '',
    image: null,
  },
  {
    id: 'CMP014',
    studentId: 'STU003',
    studentName: 'Amit Kumar',
    hostelBlock: 'A',
    roomNumber: '312',
    category: 'Other',
    description: 'Window glass is cracked. Need replacement.',
    status: 'In Progress',
    priority: 'High',
    assignedStaff: 'STF005',
    assignedStaffName: 'Vats Demo',
    createdAt: '2026-02-12T11:00:00',
    updatedAt: '2026-02-13T08:30:00',
    resolutionNotes: 'Glass ordered. Will be installed tomorrow.',
    image: null,
  },
];

// Feedback entries
export const feedbacks = [
  {
    id: 'FDB001',
    complaintId: 'CMP003',
    studentId: 'STU002',
    studentName: 'Priya Patel',
    rating: 5,
    comment: 'Excellent work! WiFi issue resolved quickly. Very satisfied with the service.',
    createdAt: '2026-02-02T10:00:00',
  },
  {
    id: 'FDB002',
    complaintId: 'CMP007',
    studentId: 'STU001',
    studentName: 'Rahul Sharma',
    rating: 4,
    comment: 'Lock was replaced properly. Took a bit longer but good work overall.',
    createdAt: '2026-01-19T09:00:00',
  },
  {
    id: 'FDB003',
    complaintId: 'CMP002',
    studentId: 'STU001',
    studentName: 'Rahul Sharma',
    rating: 3,
    comment: 'Issue is being handled but taking too long to resolve.',
    createdAt: '2026-02-07T15:30:00',
  },
  {
    id: 'FDB004',
    complaintId: 'CMP011',
    studentId: 'STU004',
    studentName: 'Vats Demo',
    rating: 5,
    comment: 'Excellent and quick service! Drawer fixed perfectly.',
    createdAt: '2026-02-11T17:00:00',
  },
];

// Complaint categories
export const categories = [
  'Electrical',
  'Plumbing',
  'WiFi',
  'Furniture',
  'Sanitation',
  'Other',
];

// Priority levels
export const priorities = ['Low', 'Medium', 'High'];

// Status options
export const statuses = ['Pending', 'In Progress', 'Resolved'];
